"""
Hado DSL — Backend Arduino/ESP32 (IoT & Hardware).
Genera codigo C++ (.ino) adaptado para microcontroladores (ESP32/ESP8266).
"""

from __future__ import annotations
from typing import List

from ..transpiler import BaseTranspiler
from ..ast_nodes import *

class ArduinoTranspiler(BaseTranspiler):
    def emit(self) -> str:
        self._arduino_includes = set()
        
        # Recorrer statements para pre-computar includes
        body_lines = []
        for stmt in self.ast.statements:
            res = self._visit(stmt)
            if res:
                body_lines.append(res)
        
        lines = [
            "/* Arduino/ESP32 Sketch generated by Hado DSL */",
            "#include <Arduino.h>"
        ]
        
        if "WiFi" in self._arduino_includes:
            lines.append("#include <WiFi.h>")
        if "HTTPClient" in self._arduino_includes:
            lines.append("#include <HTTPClient.h>")
        if "esp_wifi" in self._arduino_includes:
            lines.append("#include <esp_wifi.h>")
            
        lines.append("\nvoid setup() {")
        lines.append("    Serial.begin(115200);")
        lines.append("    delay(1000);")
        lines.append("    Serial.println(\"[hado] Initializing payload...\");\n")
        
        self._indent = 1
        lines.extend(body_lines)
        
        lines.append("}")
        lines.append("\nvoid loop() {")
        lines.append("    // Payload finished, halt")
        lines.append("    delay(10000);")
        lines.append("}")
        
        return "\n".join(lines) + "\n"

    def _ind(self) -> str:
        return "    " * self._indent

    def _visit(self, node: Node) -> str:
        method = f"_visit_{type(node).__name__}"
        visitor = getattr(self, method, self._visit_unknown)
        return visitor(node)

    def _visit_unknown(self, node: Node) -> str:
        raise NotImplementedError(f"Node not implemented in Arduino backend: {type(node).__name__}")

    def _visit_Assignment(self, node: Assignment) -> str:
        val = self._visit(node.value) if node.value else '""'
        # Tipado naivo: String by default
        type_str = "String"
        if isinstance(node.value, NumberLiteral):
            type_str = "int"
        elif isinstance(node.value, BooleanLiteral):
            type_str = "bool"
        return f"{self._ind()}{type_str} {node.name} = {val};"

    def _visit_ShowStatement(self, node: ShowStatement) -> str:
        if not node.values and node.value is None:
            return f"{self._ind()}Serial.println(\"pipe_val\");"
        val = self._visit(node.value) if node.value else self._visit(node.values[0])
        return f"{self._ind()}Serial.println({val});"

    def _visit_IfStatement(self, node: IfStatement) -> str:
        cond = self._visit(node.condition)
        lines = [f"{self._ind()}if ({cond}) {{"]
        self._indent += 1
        for stmt in node.then_body:
            lines.append(self._visit(stmt))
        self._indent -= 1
        if node.else_body:
            lines.append(f"{self._ind()}}} else {{")
            self._indent += 1
            for stmt in node.else_body:
                lines.append(self._visit(stmt))
            self._indent -= 1
        lines.append(f"{self._ind()}}}")
        return "\n".join(lines)

    def _visit_WhileStatement(self, node: WhileStatement) -> str:
        cond = self._visit(node.condition)
        lines = [f"{self._ind()}while ({cond}) {{"]
        self._indent += 1
        for stmt in node.body:
            lines.append(self._visit(stmt))
        self._indent -= 1
        lines.append(f"{self._ind()}}}")
        return "\n".join(lines)

    def _visit_ForStatement(self, node: ForStatement) -> str:
        iterable = self._visit(node.iterable)
        lines = [
            f"{self._ind()}// Iteracion generica para array",
            f"{self._ind()}for (int _i = 0; _i < 10; _i++) {{"
        ]
        self._indent += 1
        for stmt in node.body:
            lines.append(self._visit(stmt))
        self._indent -= 1
        lines.append(f"{self._ind()}}}")
        return "\n".join(lines)

    def _visit_FunctionDef(self, node: FunctionDef) -> str:
        return f"{self._ind()}// Nested/Local functions not supported in Arduino setup() scope"

    def _visit_ReturnStatement(self, node: ReturnStatement) -> str:
        if node.value:
            val = self._visit(node.value)
            return f"{self._ind()}return {val};"
        return f"{self._ind()}return;"

    def _visit_SaveStatement(self, node: SaveStatement) -> str:
        fname = self._visit(node.filename) if node.filename else '"out.txt"'
        val = self._visit(node.value) if node.value else '"pipe_val"'
        return f"{self._ind()}Serial.printf(\"[hado/SD_SAVE] %s -> %s\\n\", String({val}).c_str(), String({fname}).c_str());"

    # ─── Cyber ────────────────────────────────────────────────────────────────

    def _visit_CyberScan(self, node: CyberScan) -> str:
        self._arduino_includes.add("WiFi")
        target = self._visit(node.target) if node.target else '"127.0.0.1"'
        ports = self._visit_ListLiteral(ListLiteral(node.ports)) if node.ports else '"{}"'
        lines = [
            f"{self._ind()}{{",
            f"{self._ind()}    WiFiClient _client;",
            f"{self._ind()}    if(_client.connect({target}, 80)) {{",
            f"{self._ind()}        Serial.println(\"[hado] Port 80 Open\");",
            f"{self._ind()}    }} else {{ Serial.println(\"[hado] Port 80 Closed\"); }}",
            f"{self._ind()}    _client.stop();",
            f"{self._ind()}}}"
        ]
        return "\n".join(lines)

    def _visit_CyberRecon(self, node: CyberRecon) -> str:
        self._arduino_includes.add("WiFi")
        domain = self._visit(node.domain) if node.domain else '"example.com"'
        lines = [
            f"{self._ind()}{{",
            f"{self._ind()}    IPAddress _ip;",
            f"{self._ind()}    if(WiFi.hostByName({domain}, _ip)) {{",
            f"{self._ind()}        Serial.println(\"[hado] Recon: \" + _ip.toString());",
            f"{self._ind()}    }}",
            f"{self._ind()}}}"
        ]
        return "\n".join(lines)

    def _visit_CyberAttack(self, node: CyberAttack) -> str:
        self._arduino_includes.add("HTTPClient")
        target = self._visit(node.target) if node.target else '"127.0.0.1"'
        username = self._visit(node.username) if node.username else '"admin"'
        lines = [
            f"{self._ind()}{{",
            f"{self._ind()}    HTTPClient _http;",
            f"{self._ind()}    _http.begin({target});",
            f"{self._ind()}    _http.setAuthorization({username}, \"password\");",
            f"{self._ind()}    int _code = _http.GET();",
            f"{self._ind()}    if(_code == 200) Serial.println(\"[hado] Brute success on ESP32\");",
            f"{self._ind()}    _http.end();",
            f"{self._ind()}}}"
        ]
        return "\n".join(lines)

    def _visit_CyberCapture(self, node: CyberCapture) -> str:
        self._arduino_includes.add("esp_wifi")
        iface = self._visit(node.interface) if node.interface else '"eth0"'
        lines = [
            f"{self._ind()}{{",
            f"{self._ind()}    Serial.println(\"[hado] Init ESP32 Promiscuous mode on \" + String({iface}));",
            f"{self._ind()}    esp_wifi_set_promiscuous(true);",
            f"{self._ind()}}}"
        ]
        return "\n".join(lines)

    def _visit_CyberEnumerate(self, node: CyberEnumerate) -> str:
        self._arduino_includes.add("HTTPClient")
        target = self._visit(node.target) if node.target else '"http://127.0.0.1"'
        lines = [
            f"{self._ind()}{{",
            f"{self._ind()}    HTTPClient _http;",
            f"{self._ind()}    _http.begin(String({target}) + \"/admin\");",
            f"{self._ind()}    int _code = _http.GET();",
            f"{self._ind()}    if(_code > 0 && _code != 404) Serial.println(\"[hado] Found dir\");",
            f"{self._ind()}    _http.end();",
            f"{self._ind()}}}"
        ]
        return "\n".join(lines)

    def _visit_CyberAnalyze(self, node: CyberAnalyze) -> str:
        self._arduino_includes.add("HTTPClient")
        target = self._visit(node.source) if node.source else '"http://127.0.0.1"'
        lines = [
            f"{self._ind()}{{",
            f"{self._ind()}    HTTPClient _http;",
            f"{self._ind()}    _http.begin({target});",
            f"{self._ind()}    const char *headerKeys[] = {{\"Server\", \"X-Powered-By\"}};",
            f"{self._ind()}    _http.collectHeaders(headerKeys, 2);",
            f"{self._ind()}    _http.GET();",
            f"{self._ind()}    Serial.println(\"[hado] Header: \" + _http.header(\"Server\"));",
            f"{self._ind()}    _http.end();",
            f"{self._ind()}}}"
        ]
        return "\n".join(lines)

    def _visit_CyberFindVulns(self, node: CyberFindVulns) -> str:
        target = self._visit(node.target) if node.target else '"target"'
        return f'{self._ind()}Serial.println("[hado] Scanning vulns on " + String({target}) + " from ESP32");'

    def _visit_GenerateReport(self, node: GenerateReport) -> str:
        data = self._visit(node.data) if node.data else '""'
        return f'{self._ind()}Serial.println("[hado] UART Report Exfiltration: " + String({data}));'

    def _visit_HttpGet(self, node: HttpGet) -> str:
        self._arduino_includes.add("HTTPClient")
        url = self._visit(node.url) if node.url else '""'
        return f"\"<HTTP_GET_PENDING>\""

    def _visit_HttpPost(self, node: HttpPost) -> str:
        self._arduino_includes.add("HTTPClient")
        url = self._visit(node.url) if node.url else '""'
        return f"\"<HTTP_POST_PENDING>\""

    def _visit_ExpressionStatement(self, node: ExpressionStatement) -> str:
        return f"{self._ind()}{self._visit(node.expr)};"

    # ─── Expresiones ─────────────────────────────────────────────────────────

    def _visit_BinaryOp(self, node: BinaryOp) -> str:
        left = self._visit(node.left)
        right = self._visit(node.right)
        op_map = {"y": "&&", "o": "||", "no": "!", "es": "==", "==": "==", "!=": "!=", ">=": ">=", "<=": "<=", ">": ">", "<": "<", "+": "+", "-": "-", "*": "*", "/": "/", "%": "%"}
        op = op_map.get(node.op, node.op)
        return f'({left} {op} {right})'

    def _visit_UnaryOp(self, node: UnaryOp) -> str:
        op = "!" if node.op == "no" else "-"
        return f"({op}{self._visit(node.operand)})"

    def _visit_NumberLiteral(self, node: NumberLiteral) -> str:
        return str(node.value)

    def _visit_StringLiteral(self, node: StringLiteral) -> str:
        return node.value

    def _visit_BooleanLiteral(self, node: BooleanLiteral) -> str:
        return "true" if node.value else "false"

    def _visit_NullLiteral(self, node: NullLiteral) -> str:
        return "NULL"

    def _visit_Identifier(self, node: Identifier) -> str:
        return node.name

    def _visit_ListLiteral(self, node: ListLiteral) -> str:
        return '"{List}"'

    def _visit_DictLiteral(self, node: DictLiteral) -> str:
        return '"{Dict}"'

    def _visit_PropertyAccess(self, node: PropertyAccess) -> str:
        return f'"{node.prop}"'

    def _visit_IndexAccess(self, node: IndexAccess) -> str:
        return f"{self._visit(node.obj)}[{self._visit(node.index)}]"

    def _visit_FunctionCall(self, node: FunctionCall) -> str:
        args = ", ".join(self._visit(a) for a in node.args)
        return f"{node.func}({args})"

    def _visit_PipeExpression(self, node: PipeExpression) -> str:
        return '"" /* Pipes no soportados en Arduino */'

    def _visit_FilterExpression(self, node: FilterExpression) -> str:
        return '"" /* Filter no soportado en Arduino */'

    def _visit_SortExpression(self, node: SortExpression) -> str:
        return '"" /* Sort no soportado en Arduino */'

    def _visit_CountExpression(self, node: CountExpression) -> str:
        return f'0 /* Count simulado */'
