"""
Hado DSL — Backend JavaScript (Node.js).
Genera codigo JavaScript moderno (ESM / async/await) para Node.js.
"""

from __future__ import annotations
from typing import List

from ..transpiler import BaseTranspiler
from ..ast_nodes import *

class JavascriptTranspiler(BaseTranspiler):
    def __init__(self, ast: Program):
        super().__init__(ast)
        self._requires = set()
        self._has_main = False

    def emit(self) -> str:
        body_lines = []
        for stmt in self.ast.statements:
            result = self._visit(stmt)
            if result:
                body_lines.append(result)

        lines = ["// JavaScript generated by Hado DSL"]
        if "net" in self._requires:
            lines.append("const net = require('net');")
        if "dns" in self._requires:
            lines.append("const dns = require('dns').promises;")
        if "fs" in self._requires:
            lines.append("const fs = require('fs');")
        
        lines.append("")
        
        # Envolvemos en async IIFE si hay top level await pero para Node 18+ el top level await es nativo en ESM
        # Asumiremos Node 18+ (nativo fetch y top-level await)
        lines.append("async function main_hado() {")
        self._indent += 1
        lines.extend(f"{self._ind()}{line}" for line in body_lines)
        if self._has_main:
            lines.append(f"{self._ind()}await main();")
        self._indent -= 1
        lines.append("}")
        lines.append("main_hado().catch(console.error);")
        return "\n".join(lines) + "\n"

    def _ind(self) -> str:
        return "    " * self._indent

    def _visit(self, node: Node) -> str:
        method = f"_visit_{type(node).__name__}"
        visitor = getattr(self, method, self._visit_unknown)
        return visitor(node)

    def _visit_unknown(self, node: Node) -> str:
        return f"/* TODO: {type(node).__name__} */"

    def _visit_Assignment(self, node: Assignment) -> str:
        val = self._visit(node.value) if node.value else 'null'
        return f"let {node.name} = {val};"

    def _visit_ShowStatement(self, node: ShowStatement) -> str:
        if not node.values and node.value is None:
            return "console.log(_pipe_val);"
        vals = node.values if node.values else [node.value]
        rendered = ", ".join(self._visit(v) for v in vals)
        return f"console.log({rendered});"

    def _visit_IfStatement(self, node: IfStatement) -> str:
        cond = self._visit(node.condition)
        lines = [f"if ({cond}) {{"]
        self._indent += 1
        for stmt in node.then_body:
            lines.append(f"{self._ind()}{self._visit(stmt)}")
        self._indent -= 1
        if node.else_body:
            lines.append(f"{self._ind()}}} else {{")
            self._indent += 1
            for stmt in node.else_body:
                lines.append(f"{self._ind()}{self._visit(stmt)}")
            self._indent -= 1
        lines.append(f"{self._ind()}}}")
        return "\n".join(lines)

    def _visit_WhileStatement(self, node: WhileStatement) -> str:
        cond = self._visit(node.condition)
        lines = [f"while ({cond}) {{"]
        self._indent += 1
        for stmt in node.body:
            lines.append(f"{self._ind()}{self._visit(stmt)}")
        self._indent -= 1
        lines.append(f"{self._ind()}}}")
        return "\n".join(lines)

    def _visit_ForStatement(self, node: ForStatement) -> str:
        iterable = self._visit(node.iterable)
        lines = [f"for (let {node.var} of {iterable}) {{"]
        self._indent += 1
        for stmt in node.body:
            lines.append(f"{self._ind()}{self._visit(stmt)}")
        self._indent -= 1
        lines.append(f"{self._ind()}}}")
        return "\n".join(lines)

    def _visit_FunctionDef(self, node: FunctionDef) -> str:
        if node.name == "main":
            self._has_main = True
        params = ", ".join(node.params)
        lines = [f"async function {node.name}({params}) {{"]
        self._indent += 1
        for stmt in node.body:
            lines.append(f"{self._ind()}{self._visit(stmt)}")
        self._indent -= 1
        lines.append(f"{self._ind()}}}")
        return "\n".join(lines)

    def _visit_ReturnStatement(self, node: ReturnStatement) -> str:
        if node.value:
            val = self._visit(node.value)
            return f"return {val};"
        return "return;"

    def _visit_SaveStatement(self, node: SaveStatement) -> str:
        self._requires.add("fs")
        fname = self._visit(node.filename) if node.filename else '"out.txt"'
        val = self._visit(node.value) if node.value else "_pipe_val"
        return f"fs.writeFileSync({fname}, String({val}));"

    # ─── Cyber ────────────────────────────────────────────────────────────────

    def _visit_CyberScan(self, node: CyberScan) -> str:
        self._requires.add("net")
        target = self._visit(node.target) if node.target else '"127.0.0.1"'
        ports = self._visit_ListLiteral(ListLiteral(node.ports)) if node.ports else "[]"
        lines = [
            f"for (let _p of {ports}) {{",
            f"    await new Promise(r => {{",
            f"        const s = new net.Socket();",
            f"        s.setTimeout(1000);",
            f"        s.on('connect', () => {{ console.log(`Port ${{_p}}: open`); s.destroy(); r(); }});",
            f"        s.on('timeout', () => {{ console.log(`Port ${{_p}}: closed`); s.destroy(); r(); }});",
            f"        s.on('error', () => {{ console.log(`Port ${{_p}}: closed`); s.destroy(); r(); }});",
            f"        s.connect(_p, {target});",
            f"    }});",
            f"}}"
        ]
        return "\n".join(lines)

    def _visit_CyberRecon(self, node: CyberRecon) -> str:
        self._requires.add("dns")
        domain = self._visit(node.domain) if node.domain else '"example.com"'
        lines = [
            f"try {{",
            f"    const _res = await dns.resolve4({domain});",
            f"    console.log(`[hado] DNS Recon on ${{ {domain} }}:`, _res.join(', '));",
            f"}} catch (e) {{ console.log(`[hado] DNS Recon on ${{ {domain} }}: failed`); }}"
        ]
        return "\n".join(lines)

    def _visit_CyberAttack(self, node: CyberAttack) -> str:
        target = self._visit(node.target) if node.target else '"http://127.0.0.1"'
        username = self._visit(node.username) if node.username else '"admin"'
        wordlist = self._visit(node.wordlist) if node.wordlist else '["admin", "password"]'
        lines = [
            f"for (let _pass of {wordlist}) {{",
            f"    const _auth = Buffer.from({username} + ':' + _pass).toString('base64');",
            f"    try {{",
            f"        const _res = await fetch({target}, {{ headers: {{ 'Authorization': `Basic ${{_auth}}` }} }});",
            f"        if (_res.ok) {{",
            f"            console.log(`[hado] Brute success: ${{ {username} }}:${{_pass}}`);",
            f"            break;",
            f"        }}",
            f"    }} catch (e) {{}}",
            f"}}"
        ]
        return "\n".join(lines)

    def _visit_CyberCapture(self, node: CyberCapture) -> str:
        iface = self._visit(node.interface) if node.interface else '"eth0"'
        return f"console.log(`[hado] Capture requires pcap C++ bindings (npm install pcap) on ${{ {iface} }}`);"

    def _visit_CyberEnumerate(self, node: CyberEnumerate) -> str:
        target = self._visit(node.target) if node.target else '"http://127.0.0.1"'
        wordlist = self._visit(node.wordlist) if node.wordlist else '["admin", "login"]'
        lines = [
            f"for (let _dir of {wordlist}) {{",
            f"    try {{",
            f"        const _res = await fetch(`${{{target}}}/${{_dir}}`);",
            f"        if (_res.status !== 404) {{",
            f"            console.log(`[hado] Found: ${{ {target} }}/${{_dir}} [${{_res.status}}]`);",
            f"        }}",
            f"    }} catch (e) {{}}",
            f"}}"
        ]
        return "\n".join(lines)

    def _visit_CyberAnalyze(self, node: CyberAnalyze) -> str:
        target = self._visit(node.source) if node.source else '"http://127.0.0.1"'
        lines = [
            f"try {{",
            f"    const _res = await fetch({target}, {{ method: 'HEAD' }});",
            f"    console.log(`[hado] Headers for ${{ {target} }}:`);",
            f"    _res.headers.forEach((v, k) => console.log(`${{k}}: ${{v}}`));",
            f"}} catch (e) {{ console.log('[hado] Failed to analyze headers'); }}"
        ]
        return "\n".join(lines)

    def _visit_CyberFindVulns(self, node: CyberFindVulns) -> str:
        target = self._visit(node.target) if node.target else '"target"'
        return f"console.log(`[hado] Scanning vulns on ${{ {target} }} (integrate CVE DB API)`);"

    def _visit_GenerateReport(self, node: GenerateReport) -> str:
        self._requires.add("fs")
        data = self._visit(node.data) if node.data else "{}"
        fname = f'"{node.output_file}"' if hasattr(node, 'output_file') and node.output_file else '"report.json"'
        return f"fs.writeFileSync({fname}, JSON.stringify({data}, null, 2));\nconsole.log(`[hado] Report saved to ${{ {fname} }}`);"

    def _visit_HttpGet(self, node: HttpGet) -> str:
        url = self._visit(node.url) if node.url else '""'
        return f"(await fetch({url}).then(r => r.text()))"

    def _visit_HttpPost(self, node: HttpPost) -> str:
        url = self._visit(node.url) if node.url else '""'
        body = self._visit(node.body) if node.body else '""'
        return f"(await fetch({url}, {{ method: 'POST', body: JSON.stringify({body}) }}).then(r => r.text()))"

    def _visit_ExpressionStatement(self, node: ExpressionStatement) -> str:
        return f"{self._visit(node.expr)};"

    # ─── Expresiones ─────────────────────────────────────────────────────────

    def _visit_BinaryOp(self, node: BinaryOp) -> str:
        left = self._visit(node.left)
        right = self._visit(node.right)
        op_map = {"y": "&&", "o": "||", "no": "!", "es": "===", "==": "===", "!=": "!==", ">=": ">=", "<=": "<=", ">": ">", "<": "<", "+": "+", "-": "-", "*": "*", "/": "/", "%": "%"}
        op = op_map.get(node.op, node.op)
        return f'({left} {op} {right})'

    def _visit_UnaryOp(self, node: UnaryOp) -> str:
        op = "!" if node.op == "no" else "-"
        return f"({op}{self._visit(node.operand)})"

    def _visit_NumberLiteral(self, node: NumberLiteral) -> str:
        return str(node.value)

    def _visit_StringLiteral(self, node: StringLiteral) -> str:
        return node.value

    def _visit_BooleanLiteral(self, node: BooleanLiteral) -> str:
        return "true" if node.value else "false"

    def _visit_NullLiteral(self, node: NullLiteral) -> str:
        return "null"

    def _visit_Identifier(self, node: Identifier) -> str:
        return node.name

    def _visit_ListLiteral(self, node: ListLiteral) -> str:
        elements = ", ".join(self._visit(e) for e in node.elements)
        return f"[{elements}]"

    def _visit_DictLiteral(self, node: DictLiteral) -> str:
        pairs = []
        for k, v in node.pairs:
            pairs.append(f"[{self._visit(k)}]: {self._visit(v)}")
        return "{" + ", ".join(pairs) + "}"

    def _visit_PropertyAccess(self, node: PropertyAccess) -> str:
        return f"{self._visit(node.obj)}.{node.prop}"

    def _visit_IndexAccess(self, node: IndexAccess) -> str:
        return f"{self._visit(node.obj)}[{self._visit(node.index)}]"

    def _visit_FunctionCall(self, node: FunctionCall) -> str:
        args = ", ".join(self._visit(a) for a in node.args)
        return f"(await {node.func}({args}))"

    def _visit_PipeExpression(self, node: PipeExpression) -> str:
        lines = ["let _pipe_val = null;"]
        for i, step in enumerate(node.steps):
            if i == 0:
                val = self._visit(step)
                lines.append(f"_pipe_val = {val};")
            else:
                if isinstance(step, (ShowStatement, SaveStatement)):
                    lines.append(self._visit(step))
                else:
                    val = self._visit(step)
                    lines.append(f"_pipe_val = {val};")
        return "\n".join(lines)

    def _visit_FilterExpression(self, node: FilterExpression) -> str:
        src = self._visit(node.iterable) if node.iterable else "_pipe_val"
        cond = self._visit(node.condition)
        return f"{src}.filter({node.var} => {cond})"

    def _visit_SortExpression(self, node: SortExpression) -> str:
        src = self._visit(node.source) if node.source else "_pipe_val"
        return f"[...{src}].sort()"

    def _visit_CountExpression(self, node: CountExpression) -> str:
        src = self._visit(node.source) if node.source else "_pipe_val"
        return f"{src}.length"

