"""
Hado DSL — Backend PowerShell.
Genera codigo PowerShell para ataques "Living off the Land" en Windows (fileless).
"""

from __future__ import annotations
from typing import List

from ..transpiler import BaseTranspiler
from ..ast_nodes import *

class PowershellTranspiler(BaseTranspiler):
    def emit(self) -> str:
        lines = [
            "# PowerShell generated by Hado DSL",
            "$ErrorActionPreference = 'Stop'",
            ""
        ]
        for stmt in self.ast.statements:
            result = self._visit(stmt)
            if result:
                lines.append(result)
        return "\n".join(lines) + "\n"

    def _ind(self) -> str:
        return "    " * self._indent

    def _visit(self, node: Node) -> str:
        method = f"_visit_{type(node).__name__}"
        visitor = getattr(self, method, self._visit_unknown)
        return visitor(node)

    def _visit_unknown(self, node: Node) -> str:
        return f"# TODO: {type(node).__name__}"

    def _visit_Assignment(self, node: Assignment) -> str:
        val = self._visit(node.value) if node.value else '""'
        if isinstance(node.value, ListLiteral):
            return f"{self._ind()}${node.name} = @({val})"
        if isinstance(node.value, DictLiteral):
            return f"{self._ind()}${node.name} = @{{{val}}}"
        return f"{self._ind()}${node.name} = {val}"

    def _visit_ShowStatement(self, node: ShowStatement) -> str:
        if not node.values and node.value is None:
            return f"{self._ind()}Write-Output $_"
        vals = node.values if node.values else [node.value]
        rendered = " + ' ' + ".join(self._visit(v) for v in vals)
        return f"{self._ind()}Write-Output ({rendered})"

    def _visit_IfStatement(self, node: IfStatement) -> str:
        cond = self._visit(node.condition)
        lines = [f"{self._ind()}if ({cond}) {{"]
        self._indent += 1
        for stmt in node.then_body:
            lines.append(self._visit(stmt))
        self._indent -= 1
        if node.else_body:
            lines.append(f"{self._ind()}}} else {{")
            self._indent += 1
            for stmt in node.else_body:
                lines.append(self._visit(stmt))
            self._indent -= 1
        lines.append(f"{self._ind()}}}")
        return "\n".join(lines)

    def _visit_WhileStatement(self, node: WhileStatement) -> str:
        cond = self._visit(node.condition)
        lines = [f"{self._ind()}while ({cond}) {{"]
        self._indent += 1
        for stmt in node.body:
            lines.append(self._visit(stmt))
        self._indent -= 1
        lines.append(f"{self._ind()}}}")
        return "\n".join(lines)

    def _visit_ForStatement(self, node: ForStatement) -> str:
        iterable = self._visit(node.iterable)
        lines = [f"{self._ind()}foreach (${node.var} in {iterable}) {{"]
        self._indent += 1
        for stmt in node.body:
            lines.append(self._visit(stmt))
        self._indent -= 1
        lines.append(f"{self._ind()}}}")
        return "\n".join(lines)

    def _visit_FunctionDef(self, node: FunctionDef) -> str:
        lines = [f"{self._ind()}function {node.name} {{"]
        self._indent += 1
        if node.params:
            params = ", ".join(f"${p}" for p in node.params)
            lines.append(f"{self._ind()}param({params})")
        for stmt in node.body:
            lines.append(self._visit(stmt))
        self._indent -= 1
        lines.append(f"{self._ind()}}}")
        if node.name == "main":
            lines.append(f"{self._ind()}main")
        return "\n".join(lines)

    def _visit_ReturnStatement(self, node: ReturnStatement) -> str:
        if node.value:
            val = self._visit(node.value)
            return f"{self._ind()}return {val}"
        return f"{self._ind()}return"

    def _visit_SaveStatement(self, node: SaveStatement) -> str:
        fname = self._visit(node.filename) if node.filename else "out.txt"
        val = self._visit(node.value) if node.value else "$_"
        return f"{self._ind()}{val} | Out-File -FilePath {fname} -Encoding utf8"

    # ─── Cyber ────────────────────────────────────────────────────────────────

    def _visit_CyberScan(self, node: CyberScan) -> str:
        target = self._visit(node.target) if node.target else '"127.0.0.1"'
        ports = ", ".join(self._visit(p) for p in node.ports)
        lines = [
            f"{self._ind()}foreach ($p in @({ports})) {{",
            f"{self._ind()}    $tcp = New-Object System.Net.Sockets.TcpClient",
            f"{self._ind()}    $result = $tcp.BeginConnect({target}, $p, $null, $null)",
            f"{self._ind()}    $success = $result.AsyncWaitHandle.WaitOne(1000, $false)",
            f"{self._ind()}    if ($success) {{ Write-Output \"Port $p: open\" }} else {{ Write-Output \"Port $p: closed\" }}",
            f"{self._ind()}    if ($tcp.Connected) {{ $tcp.Close() }}",
            f"{self._ind()}}}"
        ]
        return "\n".join(lines)

    def _visit_CyberRecon(self, node: CyberRecon) -> str:
        domain = self._visit(node.domain) if node.domain else '"example.com"'
        return f'{self._ind()}Write-Output "[hado] DNS Recon on $({domain}):"; (Resolve-DnsName {domain} -ErrorAction SilentlyContinue).IPAddress'

    def _visit_CyberAttack(self, node: CyberAttack) -> str:
        target = self._visit(node.target) if node.target else '"127.0.0.1"'
        username = self._visit(node.username) if node.username else '"admin"'
        wordlist = self._visit(node.wordlist) if node.wordlist else '@("admin", "password", "123456")'
        lines = [
            f"{self._ind()}foreach ($pass in {wordlist}) {{",
            f"{self._ind()}    $pair = \"$({username}):$pass\"",
            f"{self._ind()}    $bytes = [System.Text.Encoding]::ASCII.GetBytes($pair)",
            f"{self._ind()}    $base64 = [System.Convert]::ToBase64String($bytes)",
            f"{self._ind()}    $headers = @{{ Authorization = \"Basic $base64\" }}",
            f"{self._ind()}    try {{",
            f"{self._ind()}        $res = Invoke-WebRequest -Uri {target} -Headers $headers -Method GET -UseBasicParsing -ErrorAction Stop",
            f"{self._ind()}        Write-Output \"[hado] Brute success: $pair\"",
            f"{self._ind()}        break",
            f"{self._ind()}    }} catch {{",
            f"{self._ind()}        # Continua",
            f"{self._ind()}    }}",
            f"{self._ind()}}}"
        ]
        return "\n".join(lines)

    def _visit_CyberCapture(self, node: CyberCapture) -> str:
        iface = self._visit(node.interface) if node.interface else '"eth0"'
        return f'{self._ind()}Write-Output "[hado] NetEvent packet capture stub (Pktmon requires Admin) en {iface}"'

    def _visit_CyberEnumerate(self, node: CyberEnumerate) -> str:
        target = self._visit(node.target) if node.target else '"http://127.0.0.1"'
        wordlist = self._visit(node.wordlist) if node.wordlist else '@("admin", "login")'
        lines = [
            f"{self._ind()}foreach ($dir in {wordlist}) {{",
            f"{self._ind()}    $url = \"$({target})/$dir\"",
            f"{self._ind()}    try {{",
            f"{self._ind()}        $res = Invoke-WebRequest -Uri $url -Method GET -UseBasicParsing -ErrorAction Stop",
            f"{self._ind()}        Write-Output \"[hado] Found: $url [$($res.StatusCode)]\"",
            f"{self._ind()}    }} catch {{",
            f"{self._ind()}        if ($_.Exception.Response.StatusCode -ne 404) {{ Write-Output \"[hado] Found (Auth req?): $url\" }}",
            f"{self._ind()}    }}",
            f"{self._ind()}}}"
        ]
        return "\n".join(lines)

    def _visit_CyberAnalyze(self, node: CyberAnalyze) -> str:
        target = self._visit(node.source) if node.source else '"http://127.0.0.1"'
        lines = [
            f"{self._ind()}try {{",
            f"{self._ind()}    $res = Invoke-WebRequest -Uri {target} -Method HEAD -UseBasicParsing",
            f"{self._ind()}    Write-Output \"[hado] Headers for $({target}):\"",
            f"{self._ind()}    $res.Headers | Format-Table -AutoSize",
            f"{self._ind()}}} catch {{",
            f"{self._ind()}    Write-Output \"[hado] Fallo al analizar headers\"",
            f"{self._ind()}}}"
        ]
        return "\n".join(lines)

    def _visit_CyberFindVulns(self, node: CyberFindVulns) -> str:
        target = self._visit(node.target) if node.target else '"target"'
        return f'{self._ind()}Write-Output "[hado] Scanning vulns on $({target}) (integrate external binary)"'

    def _visit_GenerateReport(self, node: GenerateReport) -> str:
        data = self._visit(node.data) if node.data else '@{}'
        fname = f'"{node.output_file}"' if hasattr(node, 'output_file') and node.output_file else '"report.json"'
        return f'{self._ind()}{data} | ConvertTo-Json | Out-File -FilePath {fname} -Encoding utf8; Write-Output "[hado] Report saved to $({fname})"'

    def _visit_HttpGet(self, node: HttpGet) -> str:
        url = self._visit(node.url) if node.url else '""'
        return f"(Invoke-WebRequest -Uri {url} -UseBasicParsing).Content"

    def _visit_HttpPost(self, node: HttpPost) -> str:
        url = self._visit(node.url) if node.url else '""'
        body = self._visit(node.body) if node.body else '""'
        return f"(Invoke-RestMethod -Uri {url} -Method POST -Body {body}).Content"

    def _visit_ExpressionStatement(self, node: ExpressionStatement) -> str:
        return f"{self._ind()}{self._visit(node.expr)}"

    # ─── Expresiones ─────────────────────────────────────────────────────────

    def _visit_BinaryOp(self, node: BinaryOp) -> str:
        left = self._visit(node.left)
        right = self._visit(node.right)
        op_map = {"y": "-and", "o": "-or", "no": "-not", "es": "-eq", "==": "-eq", "!=": "-ne", ">=": "-ge", "<=": "-le", ">": "-gt", "<": "-lt", "+": "+", "-": "-", "*": "*", "/": "/", "%": "%"}
        op = op_map.get(node.op, node.op)
        return f'({left} {op} {right})'

    def _visit_UnaryOp(self, node: UnaryOp) -> str:
        op = "-not" if node.op == "no" else "-"
        return f"({op} {self._visit(node.operand)})"

    def _visit_NumberLiteral(self, node: NumberLiteral) -> str:
        return str(node.value)

    def _visit_StringLiteral(self, node: StringLiteral) -> str:
        return node.value

    def _visit_BooleanLiteral(self, node: BooleanLiteral) -> str:
        return '$true' if node.value else '$false'

    def _visit_NullLiteral(self, node: NullLiteral) -> str:
        return '$null'

    def _visit_Identifier(self, node: Identifier) -> str:
        return f"${node.name}"

    def _visit_ListLiteral(self, node: ListLiteral) -> str:
        elements = ", ".join(self._visit(e) for e in node.elements)
        return f"@({elements})"

    def _visit_DictLiteral(self, node: DictLiteral) -> str:
        pairs = []
        for k, v in node.pairs:
            pairs.append(f"{self._visit(k)}={self._visit(v)}")
        return "@{" + "; ".join(pairs) + "}"

    def _visit_PropertyAccess(self, node: PropertyAccess) -> str:
        return f"{self._visit(node.obj)}.{node.prop}"

    def _visit_IndexAccess(self, node: IndexAccess) -> str:
        obj = self._visit(node.obj)
        idx = self._visit(node.index)
        return f"{obj}[{idx}]"

    def _visit_FunctionCall(self, node: FunctionCall) -> str:
        args = " ".join(self._visit(a) for a in node.args)
        return f"{node.func} {args}"

    def _visit_PipeExpression(self, node: PipeExpression) -> str:
        steps = [self._visit(s) for s in node.steps]
        return " | ".join(steps)

    def _visit_FilterExpression(self, node: FilterExpression) -> str:
        cond = self._visit(node.condition).replace(f"${node.var}", "$_")
        return f"Where-Object {{ {cond} }}"

    def _visit_SortExpression(self, node: SortExpression) -> str:
        return "Sort-Object"

    def _visit_CountExpression(self, node: CountExpression) -> str:
        return "Measure-Object | Select-Object -ExpandProperty Count"
